version: '3.1'

services:
  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - ./webProject:/postgresql/data
    networks:
      - my_network
  pgadmin4:
    image: dpage/pgadmin4:7.5
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ll18017@ues.edu.sv
      - PGADMIN_DEFAULT_PASSWORD=12345
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
